[package]
name = "persistwd"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
futures = "0.3"
libc = "0.2"
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
